root_urls:
  - https://ohstarkweb.myvscloud.com/webtrac/web/splash.html
max_depth: 4
refresh_days: 7
robots: true

fetch:
  mode: headless_chromium
  headless_chromium:
    wait_until: networkidle
    timeout_ms: 20000
