root_urls:
  - https://example.com/
max_depth: 1
refresh_days: 7
robots: true
# Run every 30 seconds for testing
schedule:
  type: "interval"
  seconds: 86400 # change to like 30 seconds for quicker tests
